version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092

  userapp:
    container_name: userapp
    image: ahmedeloraby/userapp
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - broker
      - zipkin
      - service-registry
    ports:
      - '8088:8080'


  controller:
    container_name: controller
    image: ahmedeloraby/controller
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - broker
      - zipkin
      - service-registry
    ports:
      - '8085:8080'

  productapp:
    container_name: productapp
    image: ahmedeloraby/productapp
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - broker
    - zipkin
    - service-registry
    ports:
      - '8089:8080'

  mediaserver:
    container_name: mediaserver
    image: ahmedeloraby/mediaapp
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - broker
      - zipkin
      - service-registry
    ports:
      - '8086:8080'
  api-gateway:
    container_name: api-gateway
    image: ahmedeloraby/api-gateway
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker

    depends_on:
      - userapp
      - productapp
      - service-registry
    ports:
      - '8001:8080'
  service-registry:
    container_name: service-registry
    image: ahmedeloraby/service-registry
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - broker
      - zipkin
    ports:
      - '8761:8761'

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2
    ports:
      - '9411:9411'