apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prodcut_Scalar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productapp
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: media_Scalar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mediaserver
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user_Scalar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userapp
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
